services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    command: npm run dev
  backend:
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
  python-backend:
    volumes:
      - ./backend/python:/app
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173

volumes:
  frontend_node_modules:
  backend_node_modules:
