services:
  frontend:
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - REACT_APP_PYTHON_API_URL=http://localhost:8000
    command: npm start
  backend:
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
  python-backend:
    volumes:
      - ./backend/python:/app
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000

volumes:
  frontend_node_modules:
  backend_node_modules:
