services:
  frontend:
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_PYTHON_API_URL=http://localhost:8000
  backend:
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://localhost:27017/trading
      - PORT=5000
  python-backend:
    volumes:
      - ./backend/python:/app
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000
