services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/trading
      - PORT=5001
    depends_on:
      - mongo
  python-backend:
    build: ./backend/python
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
      - "5173:5173"
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
volumes:
  mongo-data:
